### ISSUE TITLE
feature request: lock room setup define file and universe in registry

### ISSUE THREAD

**Issue by gac123** [alsoknownasfoo/ViveArcadeTool#4]

**Comment by alsoknownasfoo** [comment]
Are you asking to define the files that overwrite SteamVR's operating files?

**Comment by gac123** [comment]
well yes, so i do know of the location where the tool saves its "locked room" files, but I couldn't find where the universe is defined that should be locked, seeing a lighthousedb and chaperone file may contain multiple defined universes

seeing we might be doing a big expansion and having multiple venues across the country, I would generate a big lighthousedb and chaperone file and push the universe id to the registry whenever a backpack is selected to play in a specific room

**Comment by alsoknownasfoo** [comment]
Responses in Issue #2 should clarify that this is not possible. 

Closing this issue.
