### ISSUE TITLE
"set to vive pro" not always working

### ISSUE THREAD

**Issue by gac123** [alsoknownasfoo/ViveArcadeTool#6]
had this yesterday on a computer, had to disable the built in speakers device before it would finaly switch to the vive pro audio device

**Comment by alsoknownasfoo** [comment]
When this happens again, will you create a SteamVR system report and grab the log file at %localappdata%\ViveArcadeTool\app-0.8.6\log.txt and post both?

**Comment by alsoknownasfoo** [comment]
Have not received additional information for this issue in over a month.

Closing.
